import React, { useState } from "react";
import { generateEventConcept } from "../services/geminiService";
import { EventIdea, EventType } from "../types";
import { jsPDF } from "jspdf";

const AIPlanner: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [concept, setConcept] = useState<EventIdea | null>(null);
  const [formData, setFormData] = useState({
    type: EventType.WEDDING,
    city: "Melbourne",
    guests: 100,
    vibe: "Modern Elegant",
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      const result = await generateEventConcept(
        formData.type,
        formData.city,
        formData.guests,
        formData.vibe,
      );
      setConcept(result);
    } catch (error) {
      console.error("AI Generation Error:", error);
      alert("We encountered an issue crafting your concept. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!concept) return;

    const doc = new jsPDF();
    const goldColor = [235, 213, 164]; // #EBD5A4

    // Header
    doc.setFillColor(15, 23, 42); // slate-950
    doc.rect(0, 0, 210, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text("MAVEN EVENTS", 20, 22);

    doc.setTextColor(goldColor[0], goldColor[1], goldColor[2]);
    doc.setFontSize(10);
    doc.text("VISION TO REALITY | BESPOKE CONCEPTS", 20, 30);

    // Content
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text(concept.theme.toUpperCase(), 20, 60);

    doc.setDrawColor(goldColor[0], goldColor[1], goldColor[2]);
    doc.setLineWidth(0.5);
    doc.line(20, 65, 60, 65);

    doc.setFontSize(11);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100, 116, 139); // slate-500
    const splitDesc = doc.splitTextToSize(`"${concept.description}"`, 170);
    doc.text(splitDesc, 20, 75);

    let currentY = 75 + splitDesc.length * 6 + 10;

    // Venue & Decor
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("VENUE MUSE", 20, currentY);
    doc.text("THE PALETTE", 110, currentY);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105); // slate-600

    concept.venueSuggestions.forEach((venue, i) => {
      doc.text(`• ${venue}`, 20, currentY + 8 + i * 6);
    });

    const splitDecor = doc.splitTextToSize(concept.decorStyle, 80);
    doc.text(splitDecor, 110, currentY + 8);

    // Itinerary
    currentY += 40;
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("SAMPLE ITINERARY", 20, currentY);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    concept.suggestedSchedule.forEach((item, i) => {
      doc.setTextColor(goldColor[0], goldColor[1], goldColor[2]);
      doc.setFont("helvetica", "bold");
      doc.text(item.time, 20, currentY + 10 + i * 8);

      doc.setTextColor(71, 85, 105);
      doc.setFont("helvetica", "normal");
      doc.text(item.activity, 45, currentY + 10 + i * 8);
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      "Generated by Maven AI Concept Studio | mavenevents.com.au",
      105,
      285,
      { align: "center" },
    );

    doc.save(`Maven-Events-Concept-${concept.theme.replace(/\s+/g, "-")}.pdf`);
  };

  return (
    <section id="ai-planner" className="py-20 md:py-24 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12 md:mb-16">
          <h2 className="text-3xl md:text-4xl font-serif text-slate-800 mb-4">
            Maven AI Concept Studio
          </h2>
          <p className="text-slate-500 max-w-2xl mx-auto text-sm md:text-base">
            Harness the power of artificial intelligence to generate a bespoke
            event concept tailored to your specific vision.
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8 lg:gap-12 items-start">
          <div className="bg-slate-50 p-6 md:p-8 rounded-lg shadow-sm border border-slate-100">
            <h3 className="text-xl md:text-2xl font-serif mb-6 text-slate-800">
              Your Vision
            </h3>
            <form onSubmit={handleSubmit} className="space-y-4 md:space-y-6">
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                  Event Type
                </label>
                <select
                  className="w-full px-4 py-3 bg-white border border-slate-200 rounded-md focus:ring-2 focus:ring-[#EBD5A4] outline-none text-sm"
                  value={formData.type}
                  onChange={(e) =>
                    setFormData({
                      ...formData,
                      type: e.target.value as EventType,
                    })
                  }
                >
                  {Object.values(EventType).map((type) => (
                    <option key={type} value={type}>
                      {type}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                  Location (Australia)
                </label>
                <input
                  type="text"
                  placeholder="e.g. Melbourne, Byron Bay"
                  className="w-full px-4 py-3 bg-white border border-slate-200 rounded-md focus:ring-2 focus:ring-[#EBD5A4] outline-none text-sm"
                  value={formData.city}
                  onChange={(e) =>
                    setFormData({ ...formData, city: e.target.value })
                  }
                  required
                />
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                    Guest Count
                  </label>
                  <input
                    type="number"
                    className="w-full px-4 py-3 bg-white border border-slate-200 rounded-md focus:ring-2 focus:ring-[#EBD5A4] outline-none text-sm"
                    value={formData.guests}
                    onChange={(e) =>
                      setFormData({
                        ...formData,
                        guests: parseInt(e.target.value) || 0,
                      })
                    }
                    min="1"
                    required
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                    Desired Vibe
                  </label>
                  <input
                    type="text"
                    placeholder="e.g. Luxury, Boho"
                    className="w-full px-4 py-3 bg-white border border-slate-200 rounded-md focus:ring-2 focus:ring-[#EBD5A4] outline-none text-sm"
                    value={formData.vibe}
                    onChange={(e) =>
                      setFormData({ ...formData, vibe: e.target.value })
                    }
                    required
                  />
                </div>
              </div>
              <button
                type="submit"
                disabled={loading}
                className="w-full py-4 bg-slate-900 text-white font-bold uppercase tracking-widest rounded-md hover:bg-slate-800 transition-all disabled:opacity-50 text-[10px] sm:text-xs"
              >
                {loading ? (
                  <span className="flex items-center justify-center">
                    <i className="fa-solid fa-circle-notch animate-spin mr-2"></i>
                    Crafting Concept...
                  </span>
                ) : (
                  "Generate Concept"
                )}
              </button>
            </form>
          </div>

          <div className="min-h-[400px]">
            {concept ? (
              <div className="bg-white border border-maven-gold/30 p-6 md:p-8 rounded-lg shadow-xl animate-fadeIn relative">
                <div className="flex justify-between items-start mb-6">
                  <div className="flex flex-col">
                    <span className="px-2 py-1 w-fit bg-slate-100 text-[9px] font-bold rounded-full uppercase tracking-tighter mb-2">
                      AI Vision
                    </span>
                    <h3 className="text-2xl md:text-3xl font-serif text-[#EBD5A4]">
                      {concept.theme}
                    </h3>
                  </div>
                  <button
                    onClick={handleDownloadPDF}
                    className="p-3 bg-slate-50 text-slate-600 hover:text-maven-gold rounded-full border border-slate-200 transition-colors shadow-sm group"
                    title="Download PDF"
                  >
                    <i className="fa-solid fa-file-pdf text-lg group-hover:scale-110 transition-transform"></i>
                  </button>
                </div>

                <p className="text-slate-600 mb-8 leading-relaxed italic border-l-2 border-[#EBD5A4] pl-4 text-sm md:text-base">
                  "{concept.description}"
                </p>

                <div className="grid sm:grid-cols-2 gap-8">
                  <div>
                    <h4 className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-800 mb-3">
                      Venue Muse
                    </h4>
                    <ul className="space-y-2 text-slate-600">
                      {concept.venueSuggestions.map((venue, idx) => (
                        <li key={idx} className="flex items-center text-xs">
                          <i className="fa-solid fa-location-dot text-[#EBD5A4] mr-2"></i>
                          {venue}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <h4 className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-800 mb-3">
                      The Palette
                    </h4>
                    <p className="text-xs text-slate-600 leading-relaxed">
                      {concept.decorStyle}
                    </p>
                  </div>
                </div>

                <div className="mt-8 pt-8 border-t border-slate-100">
                  <h4 className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-800 mb-4">
                    Sample Itinerary
                  </h4>
                  <div className="space-y-4">
                    {concept.suggestedSchedule.map((item, idx) => (
                      <div key={idx} className="flex gap-4">
                        <span className="text-[#EBD5A4] font-bold min-w-[70px] text-xs">
                          {item.time}
                        </span>
                        <span className="text-slate-700 text-xs">
                          {item.activity}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="mt-8 flex justify-center">
                  <button
                    onClick={handleDownloadPDF}
                    className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-slate-400 hover:text-maven-gold transition-colors"
                  >
                    <i className="fa-solid fa-download"></i>
                    Export PDF Document
                  </button>
                </div>
              </div>
            ) : (
              <div className="h-full min-h-[300px] flex flex-col items-center justify-center text-center p-8 md:p-12 border-2 border-dashed border-slate-200 rounded-lg text-slate-400">
                <i className="fa-solid fa-sparkles text-4xl md:text-5xl mb-4 text-slate-200"></i>
                <p className="text-base md:text-lg font-serif italic">
                  Your bespoke concept awaits. Complete the vision form above.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};

export default AIPlanner;
